// console.log('haloo');
var test = 'true';
var lorem = [
   '<img src="img/1.jpg"></img>',
   '<img src="img/2.jpg"></img>',
   '<img src="img/3.jpg"></img>',
   '<img src="img/4.jpg"></img>',
   '<img src="img/5.jpg"></img>',
   '<img src="img/6.jpg"></img>',
   '<img src="img/7.jpg"></img>',
   '<img src="img/8.jpg"></img>',
   '<img src="img/9.jpg"></img>',
   '<img src="img/10.jpg"></img>',
   '<img src="img/11.jpg"></img>',
   '<img src="img/12.jpg"></img>',
   '<img src="img/13.jpg"></img>',
   '<img src="img/14.jpg"></img>',
   '<img src="img/15.jpg"></img>',
   '<img src="img/16.jpg"></img>',
   '<img src="img/17.jpg"></img>',
   '<img src="img/18.jpg"></img>',
   '<img src="img/19.jpg"></img>',
   '<img src="img/20.jpg"></img>',
   '<img src="img/21.jpg"></img>',
   '<img src="img/22.jpg"></img>',
   '<img src="img/23.jpg"></img>',
   '<div style="background-image: url(img/1.jpg); height: 100%; margin-top: -21px;"><h1 style="background-image: url(img/1.jpg); background-size: cover">Selaya pandang poli teknik ubaya</h1><video controls src="videos/1.mp4"></video></div>',
   '<img src="img/25.jpg"></img>',
   '<img src="img/26.jpg"></img>',
];
